baseurl         = "https://goofy-poincare-6d5a1a.netlify.app/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Dustin Allen"
  subtitle    = ""

  cover       = "images/new.jpg"
  description = "A site about Dustin Allen"
  metaDescrieption = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  linkedinName = "dustin-allen/"
  githubName = "DAludibrious"

  logo = ""
  orgName = "DA 2020"
  orgWebsite = ""
  orgDescription = "Technology Proffesional"

  author = "Dustin Allen"
  authorAvatar = "images/profile.png"
  authorLocation = "Pittsburgh, PA"
  authorWebsite = ""
  authorDescription = "IT Auditor"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/tags/about/"
  weight = 100

[[menu.main]]
  name = "Career"
  url = "/categories/career/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95