baseurl         = "https://dustinallen.netlify.app/"
theme           = "casper"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]


  title       = ""
  subtitle    = "Dustin J. Allen"

  cover       = "images/sand.jpg"
  description = "A site about Dustin Allen"
  metaDescrieption = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  linkedinName = "dustin-allen/"
  githubName = "DAludibrious"

  logo = ""
  orgName = "DA 2020"
  orgWebsite = ""
  orgDescription = "Technology Professional"

  author = "Dustin Allen"
  authorAvatar = "images/profile.png"
  authorLocation = "PA, USA"
  authorWebsite = ""
  authorDescription = "IT Auditor"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/tags/about/"
  weight = 100

[[menu.main]]
  name = "Career"
  url = "/categories/career/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95

